language: node_js
node_js:
  - 8

env:
  global:
    - SONAR_HOST=https://sonarcloud.io
    - SONAR_ORGANIZATION=croz-ltd
    - secure: "F7EnJsIb+jysu1C0D6PJxFH6vg1Hstt06iXL35gBAz4hiGK+8A/bf7c6WupK73UCIOdA/rJCnjxwzeUdWPGuujX6gy07vfqNDF1xU+t95Cy3SInlBUbRnTGQfkT51DvlW6r+80Zo5M/263vtlmUs68JkMSdY4QWmO3KxTb7l0oXL2jo5egmD5NfBc1MMJJgiO7L7NoM+wWZ0lY/u60YEoj2s1+Jb5Of0Vi99ryVPvxdH0QGVYPkifuw1rAg96TW25W0vC8yjYejbCyp8XE5wb+JhNWTGWo4AMGfzhhZg+aFf0XjiLPAaLBQlrelIpyJGwoLAAZWUWy/hegUuR/dtXn0nD0Rs7MezrV8oC9epiLMkXiguSkc5bMsqlMOAOr6uTsm78HY9bzB+osGtpJ94EjGHDlZmfwmzWBIG/KNDKYhvKJ/pZoFla9H+gZ6INMwuuVt6SJsVKf3X58iulAsz91FFjnUmh+h4fdq54bheyBt4hjx07DIz31leIE5Jr2VHAz+Y7XKvFNfuQlJqWZ05ZaNU5+mknOWx/JGrDiprTIwDbbEa0MyTS3TxXJjibFQ7hhp3u4DeRUBzQvAWVT9XOz3CpxOYOYc/JaktPlrIiHB2dvAnOGX5Al9rGdXKoRKDe/Opy/1oYPgs6H+13D6qgR20/9DCwQ+YYN7RANMH3gU"

script:
  - npm install --only=dev
  - npm install
  - npm run sonar